# Generated by Django 3.2.7 on 2022-05-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yvidh', '0002_rename_img_gal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gal',
            name='disc',
            field=models.TextField(default='hi', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gal',
            name='discc',
            field=models.TextField(default='welcome all ', max_length=200),
            preserve_default=False,
        ),
    ]
