# Generated by Django 3.2.7 on 2022-05-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yvidh', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.IntegerField(),
        ),
    ]
