# Generated by Django 3.2.7 on 2022-05-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yvidh', '0005_auto_20220526_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=models.TextField(max_length=10),
        ),
    ]
