# Generated by Django 3.2.7 on 2022-05-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yvidh', '0006_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static')),
                ('date', models.IntegerField()),
                ('month', models.TextField(max_length=100)),
                ('disc', models.TextField(max_length=100)),
                ('discc', models.TextField(max_length=300)),
            ],
        ),
    ]
