# Generated by Django 3.2.7 on 2022-05-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yvidh', '0007_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='disc',
            new_name='event_name',
        ),
    ]
