# Generated by Django 3.2.7 on 2022-05-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yvidh', '0008_rename_disc_event_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font', models.TextField()),
                ('size', models.IntegerField()),
            ],
        ),
    ]
