# Generated by Django 3.2.7 on 2022-05-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yvidh', '0009_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='color',
            field=models.TextField(default='red'),
            preserve_default=False,
        ),
    ]
